server:
  port: 8080
management:
  server:
    port: 8081
  metrics:
    web:
      server:
        auto-time-requests: true
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: ['prometheus']